import Link from "next/link";
const solvers=[["Thermal conduction","Bounded steady conduction"],["Linear structural 1D","Axial bar and cantilever beam"],["Modal eigen 1D","Mass-spring and cantilever modes"],["Acoustic duct 1D","Straight lossless plane-wave duct"],["Electrostatic 2D","Uniform rectangular grid"],["Laminar channel CFD","Plane-Poiseuille flow, Re < 2000"],["One-way thermal–structural","Sequential bounded coupling"]];
export default function HomePage(){return <main>
  <header className="public-nav"><Link className="brand" href="/">ASRE<span>–Lab</span></Link><nav aria-label="Public navigation"><a href="#product">Product</a><a href="#workflow">How It Works</a><a href="#trust">Scientific Trust</a><a href="#physics">Supported Physics</a><Link href="/scientific-scope">Scientific Scope</Link></nav><div className="nav-actions"><Link href="/auth/log-in">Log In</Link><Link className="button" href="/auth/sign-up">Get Started</Link></div></header>
  <section className="hero" id="product"><div><p className="eyebrow">Autonomous Smart Reverse Engineering Laboratory</p><h1>From engineering concept to evidence-backed decision.</h1><p className="lede">A reproducible engineering laboratory for bounded simulation, scientific validation, design comparison, and evidence-backed decisions.</p><div className="hero-actions"><Link className="button" href="/auth/sign-up">Start an engineering study</Link><Link className="button secondary" href="/scientific-scope">Review scientific scope</Link></div></div><div className="hero-panel" aria-label="Engineering workflow preview"><p className="eyebrow">REPRODUCIBLE WORKFLOW</p>{["Design","Physics","Validation","Execution","Evidence","Decision","Report"].map((x,i)=><div className="stage-row" key={x}><span>{i+1}</span><strong>{x}</strong><small>{i<3?"Define and verify":"Evidence-linked output"}</small></div>)}</div></section>
  <section className="section" id="workflow"><p className="eyebrow">HOW IT WORKS</p><h2>One traceable path through the engineering study</h2><div className="feature-grid">{[["01 · Define","Set bounded geometry, material, boundary conditions, objectives, and constraints."],["02 · Validate","Check every solver input against its declared validity envelope before execution."],["03 · Execute","Seal a reproducible manifest, monitor durable attempts, and retain artifacts privately."],["04 · Decide","Compare evidence, inspect sensitivity and ranking, then require a human decision."]].map(([h,p])=><article className="card" key={h}><h3>{h}</h3><p>{p}</p></article>)}</div></section>
  <section className="section split" id="trust"><div><p className="eyebrow">SCIENTIFIC TRUST</p><h2>Confidence with reasons, not a decorative score.</h2><p>ASRE-Lab records validity findings, assumptions, benchmark evidence, convergence evidence, limitations, solver identity, and reproducibility checksums. Confidence is reported only as high, moderate, low, or invalid.</p></div><div className="card evidence-card"><span className="status success">VALID WITH WARNINGS</span><h3>Evidence is inspectable</h3><ul><li>Declared physical model and limits</li><li>Rule-coded validity findings</li><li>Analytical benchmark comparison</li><li>Accessible convergence evidence</li></ul></div></section>
  <section className="section" id="physics"><p className="eyebrow">SUPPORTED PHYSICS</p><h2>Purposefully bounded numerical models</h2><div className="solver-grid">{solvers.map(([a,b])=><article className="solver" key={a}><strong>{a}</strong><span>{b}</span></article>)}</div></section>
  <section className="section scope-note"><h2>Scientific scope is a product feature.</h2><p>ASRE-Lab does not claim general-purpose 3D FEA or CFD, industrial certification, arbitrary CAD meshes, turbulence, plasticity, autonomous approval, or a runnable general multiphysics solver.</p><Link className="button secondary" href="/scientific-scope">Read the complete scope</Link></section>
  <footer><span>© {new Date().getFullYear()} ASRE–Lab</span><span>Bounded engineering simulation · Human-reviewed recommendations</span></footer>
</main>}
