import Link from "next/link";

const capabilities = [
  ["Create CAD variants", "Start with one supported design and vary dimensions or parameters automatically."],
  ["Run physics simulations", "Evaluate each design using the same supported physical model and controlled conditions."],
  ["Compare results", "See how changes in geometry affect physical behavior."],
  ["Analyze the design space", "Study relationships, sensitivity, rankings, and trade-offs across multiple designs."],
  ["Review the evidence", "See what was validated, what was not tested, and where every result came from."],
  ["Make the final decision", "ASRE-Lab supports the analysis. You remain responsible for the engineering decision."],
];
const workflow = ["Define your design", "Generate controlled CAD variants", "Configure the physics", "Run comparative simulations", "Analyze the results", "Review scientific evidence", "Make a human decision and export the report"];
const supportedAreas = ["thermal conduction", "limited structural mechanics", "modal analysis", "acoustics", "electrostatics", "laminar channel flow", "limited sequential thermal-structural coupling"];
const exclusions = ["arbitrary 3D FEA", "general CFD", "turbulence", "nonlinear material behavior", "unrestricted multiphysics", "autonomous engineering approval"];

export default function HomePage() {
  return <main className="landing-page">
    <header className="public-nav"><Link className="brand" href="/">ASRE-Lab</Link><nav aria-label="Public navigation"><a href="#what-you-can-do">What it does</a><a href="#workflow">How it works</a><a href="#limits">Limits</a><Link href="/scientific-scope">Scientific Scope</Link></nav><div className="nav-actions"><Link href="/auth/log-in">Log In</Link><Link className="button" href="/auth/sign-up">Start an Engineering Study</Link></div></header>
    <section className="landing-hero" id="product"><div className="landing-intro"><p className="eyebrow">Autonomous Smart Reverse Engineering Laboratory</p><h1>Design it. Simulate it. Compare it. Understand it.</h1><p className="landing-subheading">Turn one engineering design into a complete, evidence-backed comparative study.</p><p className="lede">ASRE-Lab helps you create controlled CAD variants, run supported physics simulations, compare their behavior, analyze the results, and keep the scientific evidence connected to every conclusion.</p><div className="hero-actions"><Link className="button" href="/auth/sign-up">Start an Engineering Study</Link><a className="button secondary" href="#workflow">See How It Works</a></div></div><aside className="landing-trace" aria-label="Engineering study progression"><p className="eyebrow">CONTROLLED STUDY</p>{workflow.map((stage, index) => <div className="landing-trace-row" key={stage}><span>{String(index + 1).padStart(2, "0")}</span><strong>{stage}</strong></div>)}</aside></section>
    <section className="landing-section landing-capabilities" id="what-you-can-do"><header><p className="eyebrow">PRACTICAL WORKFLOW</p><h2>What can you actually do with ASRE-Lab?</h2><p>Instead of rebuilding every CAD model, running every simulation separately, and organizing the results by hand, ASRE-Lab connects the workflow inside one research workspace.</p></header><div>{capabilities.map(([title, detail], index) => <article className="landing-card" key={title}><span>{String(index + 1).padStart(2, "0")}</span><h3>{title}</h3><p>{detail}</p></article>)}</div></section>
    <section className="landing-section landing-workflow" id="workflow"><header><p className="eyebrow">HOW IT WORKS</p><h2>From one idea to a complete engineering study</h2></header><ol>{workflow.map((stage, index) => <li key={stage}><span>{String(index + 1).padStart(2, "0")}</span><strong>{stage}</strong></li>)}</ol></section>
    <section className="landing-section landing-example"><header><p className="eyebrow">CONTROLLED EXAMPLE</p><h2>See it in a real example</h2></header><div><p>You want to know how pyramid height affects thermal behavior.</p><p>Keep the base, material, heat source, and boundary conditions fixed. Change only the height.</p><p>ASRE-Lab creates the design variants, runs the same thermal model on each one, compares their temperatures, analyzes the relationship, and preserves the evidence behind the result.</p><div className="landing-variation" aria-label="Pyramid height variants"><span>1 m</span><span>2 m</span><span>3 m</span><span>4 m</span><span>5 m</span></div></div></section>
    <section className="landing-section landing-audience"><header><p className="eyebrow">FIT</p><h2>Is ASRE-Lab for you?</h2><p>ASRE-Lab may be useful if you want to:</p></header><ul><li>Explore how geometry changes physical behavior.</li><li>Compare several versions of one engineering design.</li><li>Reduce repetitive CAD and simulation work.</li><li>Run controlled comparative engineering studies.</li><li>Analyze multiple simulation results as one dataset.</li><li>Keep results, evidence, decisions, and reports connected.</li></ul><p className="landing-audience-line">Researchers · Engineering students · Technical teams · Independent builders</p></section>
    <section className="landing-section landing-limits" id="limits"><header><p className="eyebrow">DECLARED LIMITS</p><h2>What ASRE-Lab is not</h2></header><p>ASRE-Lab is not a general-purpose replacement for professional CAD, FEA, CFD, or multiphysics software.</p><p>It uses specific supported geometries and bounded physics models so that results remain inside clearly defined scientific assumptions.</p><div className="landing-limit-grid"><section><h3>Supported areas</h3><ul>{supportedAreas.map(item => <li key={item}>{item}</li>)}</ul></section><section><h3>Not claimed</h3><ul>{exclusions.map(item => <li key={item}>{item}</li>)}</ul></section></div><Link className="button secondary" href="/scientific-scope">Scientific Scope</Link></section>
    <section className="landing-final-cta"><p className="eyebrow">START HERE</p><h2>Ready to test a design?</h2><p>Create a controlled engineering study and see how changing the design changes the physics.</p><Link className="button" href="/auth/sign-up">Start an Engineering Study</Link></section>
    <footer><span>Copyright {new Date().getFullYear()} ASRE-Lab</span><span>Bounded engineering simulation · Human-reviewed recommendations</span></footer>
  </main>;
}
