import Link from "next/link";

const solvers = [["Thermal conduction", "Bounded steady conduction"], ["Linear structural 1D", "Axial bar and cantilever beam"], ["Modal eigen 1D", "Mass-spring and cantilever modes"], ["Acoustic duct 1D", "Straight lossless plane-wave duct"], ["Electrostatic 2D", "Uniform rectangular grid"], ["Laminar channel CFD", "Plane-Poiseuille flow, Re < 2000"], ["One-way thermal-structural", "Sequential bounded coupling"]];
const workflow = [["01", "Define", "Set bounded geometry, material, boundary conditions, objectives, and constraints."], ["02", "Validate", "Check every solver input against its declared validity envelope before execution."], ["03", "Execute", "Seal a reproducible manifest, monitor durable attempts, and retain artifacts privately."], ["04", "Decide", "Compare evidence, inspect sensitivity and ranking, then require a human decision."]];

export default function HomePage() { return <main className="landing-page">
  <header className="public-nav"><Link className="brand" href="/">ASRE-Lab</Link><nav aria-label="Public navigation"><a href="#product">Product</a><a href="#workflow">How It Works</a><a href="#trust">Scientific Trust</a><a href="#physics">Supported Physics</a><Link href="/scientific-scope">Scientific Scope</Link></nav><div className="nav-actions"><Link href="/auth/log-in">Log In</Link><Link className="button" href="/auth/sign-up">Get Started</Link></div></header>
  <section className="landing-hero" id="product"><div className="landing-intro"><p className="eyebrow">Autonomous Smart Reverse Engineering Laboratory</p><h1>From engineering concept to evidence-backed decision.</h1><p className="lede">A reproducible engineering laboratory for bounded simulation, scientific validation, design comparison, and evidence-backed decisions.</p><div className="hero-actions"><Link className="button" href="/auth/sign-up">Start an engineering study</Link><Link className="button secondary" href="/scientific-scope">Review scientific scope</Link></div></div><aside className="landing-trace" aria-label="Engineering workflow preview"><p className="eyebrow">REPRODUCIBLE WORKFLOW</p>{["Design", "Physics", "Validation", "Execution", "Evidence", "Decision", "Report"].map((stage, index) => <div className="landing-trace-row" key={stage}><span>{String(index + 1).padStart(2, "0")}</span><strong>{stage}</strong><small>{index < 3 ? "Define and verify" : "Evidence-linked output"}</small></div>)}</aside></section>
  <section className="landing-section landing-workflow" id="workflow"><header><p className="eyebrow">HOW IT WORKS</p><h2>One traceable path through the engineering study</h2></header><ol>{workflow.map(([index, title, detail]) => <li key={index}><span>{index}</span><div><h3>{title}</h3><p>{detail}</p></div></li>)}</ol></section>
  <section className="landing-section landing-trust" id="trust"><div><p className="eyebrow">SCIENTIFIC TRUST</p><h2>Confidence with reasons, not a decorative score.</h2><p>ASRE-Lab records validity findings, assumptions, benchmark evidence, convergence evidence, limitations, solver identity, and reproducibility checksums. Confidence is reported only as high, moderate, low, or invalid.</p></div><dl><div><dt>Declared model</dt><dd>Physical model and limits</dd></div><div><dt>Validity</dt><dd>Rule-coded findings</dd></div><div><dt>Benchmark</dt><dd>Analytical comparison</dd></div><div><dt>Convergence</dt><dd>Accessible evidence</dd></div></dl></section>
  <section className="landing-section landing-physics" id="physics"><header><p className="eyebrow">SUPPORTED PHYSICS</p><h2>Purposefully bounded numerical models</h2></header><div className="solver-ledger">{solvers.map(([name, description]) => <article key={name}><strong>{name}</strong><span>{description}</span></article>)}</div></section>
  <section className="landing-scope"><p className="eyebrow">DECLARED LIMITS</p><h2>Scientific scope is a product feature.</h2><p>ASRE-Lab does not claim general-purpose 3D FEA or CFD, industrial certification, arbitrary CAD meshes, turbulence, plasticity, autonomous approval, or a runnable general multiphysics solver.</p><Link className="button secondary" href="/scientific-scope">Read the complete scope</Link></section>
  <footer><span>Copyright {new Date().getFullYear()} ASRE-Lab</span><span>Bounded engineering simulation · Human-reviewed recommendations</span></footer>
</main>; }
