import {getSupabase} from "./supabase";
export class ApiError extends Error{constructor(public status:number,message:string,public code?:string){super(message)}}
function proxyPath(path:string){return `/_asre-api${path.startsWith("/")?path:`/${path}`}`}
type ApiErrorBody={detail?:unknown;message?:unknown;code?:unknown};
function readableField(location:unknown){if(!Array.isArray(location))return "";const field=location.filter(part=>part!=="body"&&part!=="query"&&part!=="path").map(String).join(" → ");return field?`${field}: `:""}
function errorText(value:unknown):string{if(typeof value==="string")return value;if(typeof value==="number"||typeof value==="boolean")return String(value);if(Array.isArray(value)){const messages=value.map(errorText).filter(Boolean);return messages.join("; ")}if(value&&typeof value==="object"){const item=value as Record<string,unknown>;const message=typeof item.msg==="string"?item.msg:typeof item.message==="string"?item.message:typeof item.detail==="string"?item.detail:"";if(message)return `${readableField(item.loc)}${message}`;const nested=Object.entries(item).filter(([key])=>!['loc','type','code'].includes(key)).map(([key,child])=>`${readableField([key])}${errorText(child)}`).filter(Boolean);return nested.join("; ")}return ""}
export function normalizeApiError(body:unknown){const data=(body&&typeof body==="object"?body:{}) as ApiErrorBody;return errorText(data.detail??data.message??body)||"The request could not be completed. Check the highlighted values and try again."}
export async function api<T>(path:string,init:RequestInit&{idempotencyKey?:string}={}):Promise<T>{const {data}=await getSupabase().auth.getSession();if(!data.session)throw new ApiError(401,"Your session has expired.");const headers=new Headers(init.headers);headers.set("Authorization",`Bearer ${data.session.access_token}`);if(init.body&&!headers.has("Content-Type"))headers.set("Content-Type","application/json");if(init.idempotencyKey)headers.set("Idempotency-Key",init.idempotencyKey);const response=await fetch(proxyPath(path),{...init,headers});if(response.status===401)await getSupabase().auth.signOut();if(!response.ok){const body=await response.json().catch(()=>null);const code=body&&typeof body==="object"&&typeof (body as ApiErrorBody).code==="string"?String((body as ApiErrorBody).code):undefined;throw new ApiError(response.status,normalizeApiError(body),code)}return response.json() as Promise<T>}
export async function download(path:string){const {data}=await getSupabase().auth.getSession();if(!data.session)throw new ApiError(401,"Sign in to download this artifact.");const response=await fetch(proxyPath(path),{headers:{Authorization:`Bearer ${data.session.access_token}`}});if(!response.ok)throw new ApiError(response.status,"The artifact is unavailable.");return{blob:await response.blob(),disposition:response.headers.get("content-disposition")}}
type DownloadArtifact={blob:Blob;disposition:string|null}
function artifactFilename(disposition:string|null,fallback:string){const match=disposition?.match(/filename\*?=(?:UTF-8''|\")?([^\";\r\n]+)/i);if(!match)return fallback;try{const filename=decodeURIComponent(match[1].trim());return filename&&/^[\w.() -]+$/.test(filename)?filename:fallback}catch{return fallback}}
export function startArtifactDownload(artifact:DownloadArtifact,fallbackFilename:string,failureMessage="Artifact download failed. Please try again."){if(!artifact.blob.size)throw new Error(failureMessage);let url="";let anchor:HTMLAnchorElement|undefined;try{url=URL.createObjectURL(artifact.blob);anchor=document.createElement("a");anchor.href=url;anchor.download=artifactFilename(artifact.disposition,fallbackFilename);anchor.style.display="none";document.body.appendChild(anchor);anchor.click();anchor.remove();window.setTimeout(()=>URL.revokeObjectURL(url),0);return anchor.download}catch{anchor?.remove();if(url)URL.revokeObjectURL(url);throw new Error(failureMessage)}}
